### PR TITLE
v1.7.1 - Fixed issues with outdated typings.

### PR DESCRIPTION
**Pull request by lukeshiru**
The typings were outdated and TypeScript wasn't compiling. This PR fixes the issue.

### CODE REVIEW

**Comment by WebReflection** [comment]
what about all other `this: HTMLElement` ?

**Comment by lukeshiru** [comment]
@WebReflection afaik the conflicting lines were the ones changed by my PR. All the other lines aren't throwing any kind of errors.

**Comment by WebReflection** [comment]
sorry @lukeshiru , I do appreciate your PR, but I don't understand it, hence it won't land if I don't understand why only those methods needs `this:HTMLElement` since every other method would have the exact same signature.

Was it failing because of the `ClipboardEvent` your intelligence doesn't know? If that's the case, can you please remove all `this:HTMLElement` or add the same to every other `on*` method?

Thanks for your patience

**Comment by lukeshiru** [comment]
This is the list of errors being thrown by TypeScript when running `tsc` using `hyperHTML-Element`:
```plain
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'onactivate' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'onbeforeactivate' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'onbeforecopy' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'onbeforecut' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'onbeforedeactivate' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'onbeforepaste' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'ondeactivate' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(3,11): error TS2430: Interface 'HyperHTMLElement<T>' incorrectly extends interface 'HTMLElement'.
  Types of property 'onended' are incompatible.
    Type '(ev: UIEvent) => void' is not assignable to type '((this: HTMLElement, ev: Event) => any) | null'.
      Type '(ev: UIEvent) => void' is not assignable to type '(this: HTMLElement, ev: Event) => any'.
        Types of parameters 'ev' and 'ev' are incompatible.
          Type 'Event' is not assignable to type 'UIEvent'.
            Property 'detail' is missing in type 'Event'.
/node_modules/hyperhtml-element/index.d.ts(52,37): error TS2304: Cannot find name 'MSManipulationEvent'.
```
As soon as I changed every one of those methods to match the specification in [lib.d.ts](https://github.com/Microsoft/TypeScript/blob/master/lib/lib.d.ts#L9690) it stopped throwing errors.

**Comment by lukeshiru** [comment]
And btw, there is nothing to be sorry about @WebReflection .... obviously you can't merge anything without understanding what the PR is doing to the repo! 👍

**Comment by WebReflection** [comment]
OK, let's say you also change `onabort(ev: UIEvent): void;` as ``onabort(this: HTMLElement, ev: Event): any;` what happens?

**Pull request merged**
